### ISSUE TITLE
Leaked API key

### ISSUE THREAD

**Issue by zachllee** [anyscale/hermetic#2]
API keys are present in example [factuality_evaluation_answer_first.ipynb](https://github.com/anyscale/hermetic/blob/main/example_projects/factuality_eval/factuality_evaluation_answer_first.ipynb), [factuality_evaluation_answer_last.ipynb](https://github.com/anyscale/hermetic/blob/main/example_projects/factuality_eval/factuality_evaluation_answer_last.ipynb) notebooks, I didn't look at every file, but they seem to be in most of the notebooks

**Comment by waleedkadous** [comment]
Thanks for the heads up. The keys have been revoked. Removing the files now.
